var data = {
    "nodes": [{
        "name": "存量营销\n(同网)",
        "image": "img/user.png",
        "status": 0
    }, {
        "name": "营销活动\n接口服务",
        "image": "img/tomcat.png",
        "status": 1
    }, {
        "name": "用户划配",
        "image": "img/mysql.png",
        "status": 1
    }, {
        "name": "短信接口\n服务",
        "image": "img/user.png",
        "status": 0
    }, {
        "name": "短信渠道",
        "image": "img/mysql.png",
        "status": 0
    }, {
        "name": "工单中心",
        "image": "img/tomcat.png",
        "status": 0
    }],
    "edges": [{
        "source": 5,
        "target": 0,
        "relation": "1718"
    }, {
        "source": 5,
        "target": 2,
        "relation": "1718"
    }, {
        "source": 1,
        "target": 3,
        "relation": "1718"
    }, {
        "source": 1,
        "target": 2,
        "relation": "1718"
    }, {
        "source": 2,
        "target": 4,
        "relation": "1718"
    }, {
        "source": 1,
        "target": 1,
        "relation": "1718"
    }, {
        "source": 4,
        "target": 2,
        "relation": "1718"
    }]
};