var data = {
    "nodes": [{
        "name": "存量营销(同网)",
        "image": "img/user.png",
        "key": "11"
    }, {
        "name": "营销活动接口服务",
        "image": "img/tomcat.png",
        "key": "22"
    }, {
        "name": "用户划配",
        "image": "img/mysql.png",
        "key": "33"
    }, {
        "name": "fdafafawefwaefwef",
        "image": "img/user.png",
        "key": "44"
    }, {
        "name": "USER",
        "image": "img/mysql.png",
        "key": "55"
    }, {
        "name": "工单中心",
        "image": "img/tomcat.png",
        "key": "00"
    }],
    "edges": [{
        "source": "00",
        "target": "11",
        "relation": "17",
        "status": "fast"
    }, {
        "source": "00",
        "target": "33",
        "relation": "1718",
        "status": "fast"
    }, {
        "source": "22",
        "target": "44",
        "relation": "5",
        "status": "slow"
    }, {
        "source": "22",
        "target": "33",
        "relation": "24324234",
        "status": "slow"
    }, {
        "source": "33",
        "target": "55",
        "relation": "79",
        "status": "normal"
    }, {
        "source": "22",
        "target": "22",
        "relation": "354",
        "status": "slow"
    }, {
        "source": "55",
        "target": "33",
        "relation": "7718",
        "status": "slow"
    }]
};